### ISSUE TITLE
Events component: Events start on wrong page

### ISSUE THREAD

**Issue by aerugo** [edgeryders/webkit_components#12]
It looks like the event component starts getting events on page 1, missing all topics on page 0. This should be fixed. New endpoints are also paginated, so dealing with pagination should be built into components.

https://github.com/edgeryders/webkit_components/blob/cf6bab2911207262043a54d263e8572e7c8f0d0f/src/components/Events.vue#L246

**Comment by owengot** [comment]
Fixed and iterates paginated response to collect all events.
