### ISSUE TITLE
Topic component: Toggle sort by (alphabetical, updated, created)

### ISSUE THREAD

**Issue by aerugo** [edgeryders/webkit_components#29]
Want to be able to pass a parameter to the topic component that sorts the topics by either alphabetical, updated, created.

**Comment by owengot** [comment]
Topics can now be sorted by any topic property using the following syntax in `data/config.json`:

`"sort_by": {
        "property": "created_at"
  }`

By default, the order is `descending`. This can be reversed by specifying an order value in `data.config` (either `ascending` or `descending`):

`"sort_by": {
        "property": "title",
        "order": "ascending"
      }
`

To sort by updated time value the object would be:

`"sort_by": {
        "property": "bumped_at"
  }`
