### ISSUE TITLE
Topic "featured" slider glitchy.

### ISSUE THREAD

**Issue by aerugo** [edgeryders/webkit_components#31]
For some reason, different sets of topics render different behavior. See featured stories slider here: https://youthful-brown-c96bcf.netlify.com/#about

Slider does not "slide" previous content away, but seems to reload with new content.

If another tag is chosen, like https://edgeryders.eu/tags/webcontent-wellbeing-featured, it behaves normally.

**Comment by owengot** [comment]
Fixed in last commit.
