### ISSUE TITLE
Event serializer should get cooked post

### ISSUE THREAD

**Issue by aerugo** [edgeryders/webkit_components#39]
Events often contain more information than fits in the excerpt, so we need the full cooked post.

**Comment by gdpelican** [comment]
This fix has been merged into the master branch of the `discourse-webkit-components` plugin and should be ready for installation @aerugo :D

**Comment by aerugo** [comment]
Hmm, can't see it. Is it possible that you only merged locally?

**Comment by gdpelican** [comment]
It doesn't appear that the latest version of the plugin has been installed to `edgeryders.eu`?

**Comment by aerugo** [comment]
Ah, I see what's going on, update was on your fork. Will merge.
