### ISSUE TITLE
XML comments in the configuration post result in visualizing a blank page

### ISSUE THREAD

**Issue by albertocottica** [edgeryders/webkit_components#56]
We want to be able to insert comments in the configuration post, especially in the template that people are going to start from to make a new website ([see](https://edgeryders.eu/t/a-note-on-the-philosophy-of-the-webkit-and-its-documentation/13916/16?u=alberto)). However, this is now not possible: inserting a comment in the configuration post results in a blank page being displayed

**Comment by owengot** [comment]
Fixed in https://github.com/edgeryders/webkit
