### ISSUE TITLE
Make the color of the hyperlinks dependent on the site's color scheme

### ISSUE THREAD

**Issue by albertocottica** [edgeryders/webkit_components#57]
All hyperlinks are rendered in default WWW blue, which for most websites is at odds with the color scheme.

![image](https://user-images.githubusercontent.com/1976806/87012268-552fba80-c1c9-11ea-9db9-caf99dbc91da.png)

**Comment by owengot** [comment]
Fixed in - https://github.com/edgeryders/webkit
