### ISSUE TITLE
Hero banner component

### ISSUE THREAD

**Issue by aerugo** [edgeryders/webkit_components#8]
A simple Hero banner component, similar to that at https://sensestack.netlify.com

Input data:
* Title 
* Subtitle 
* Action buttons, titles and urls
* Background image or video

**Comment by owengot** [comment]
Added options for background image and video 

Pending: actionable links/text component

**Comment by aerugo** [comment]
@owengot 
Hero banner is not working properly. 

It loads slower than other components. It needs to load and display even before it gets the data. In fact, all components should display even when there is no data. You can use defaults for this.
[hero-slow-load.mov.zip](https://github.com/edgeryders/webkit_components/files/4213719/hero-slow-load.mov.zip)

Also, I can't custom configuration to work. How is it configured?
